services:
  - type: web
    name: student-management-backend
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8081
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
