spring.application.name=student-management
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:student_management;MODE=MySQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:suchi@21}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
server.port=${PORT:8081}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
